### ISSUE TITLE
Decide on in-person conference physical location(s)

### ISSUE THREAD

**Issue by hidyverse** [resbazaz/festival2024#17]
@brandon-jernigan @kepplerm @TinaJAZ 

Hi logistics sub-committee,

Can we brainstorm some options here and then poll for top choices? 
I need this info to get started on sponsorships.

**Comment by jcoliver** [comment]
Library. I am obviously biased. :grin:

**Comment by brandon-jernigan** [comment]
Hi! Miriam and I looked at the [EDU211](https://ctsrooms.arizona.edu/rooms/332) option, there is a cost for it, but it looks like a decent space.

Julian and I did a walkthrough of 2 options for the main library, Catalyst Studios (where it was last year) , and the bottom section of ILC (where it was in 2018). Julian shared pictures of the 2018 festival, and personally I thought it looked like really nice area to hold it. It's big and open with large windows to the outside courtyard. The courtyard will have plenty of shade for May. And there is a big presentation room, so seems like it could handle both unconference and conference style events.

Are there any other places to consider? Any other opinions on this?

**Comment by julianpistorius** [comment]
@jcoliver is it OK to have food & beverages in the ILC?

**Comment by jcoliver** [comment]
@julianpistorius Indeed.

**Comment by hidyverse** [comment]
[Decided by discussion](https://github.com/resbazaz/festival2024/discussions/19)
