### ISSUE TITLE
How do attendees communicate?

### ISSUE THREAD

**Issue by val-pf** [resbazaz/festival2024#25]
Hello, 
what is the preferred way of allowing communication between attendees, and possibly attendees and speakers?
GIthub?
Slack?
Gitter @julianpistorius  ?
hackMD?
etherpad?
...???
Discuss please!

**Comment by val-pf** [comment]
Here's my thoughts:
Hack MD:
- love how accessible they are, but might need to 'teach' how to use them
- last year, having two large hackMDs did not work well
- two years ago, one hackMD per session was challenging to navigate for attendees
Slack:
- two years ago, everyone HAD to join slack, we still have ~300 zombie accounts in the slack from that, and engagement in those channels was fairly low
- we do miss out on people if we ONLY use slack for communication
- retrograde amnesia

**Comment by jcoliver** [comment]
Depends on primary goals of communication.

+ For IMs, Slack is pretty nice (acknowledging great points by Val, above, :zombie: ).
+ If there are announcements that need to go to everyone (more one-way messaging), then...e-mail? :sauropod: 
+ Collaborative documents - vanilla Google Docs can work pretty well, although they don't really allow some of us to flex our markdown :muscle: :nerd_face:

**Comment by hidyverse** [comment]
Did we land on just e-mail?

**Comment by lwdozal** [comment]
Not to overwhelm our webmaster, but is there a way to have some type of announcements on the webiste? like put a social media or slack feed, or have the 'vanilla' google doc/google sheet on the page?

Or do we want a space where participants can comment back and ask questions?

**Comment by julianpistorius** [comment]
I would vote for Gitter. And I would set up a bridge from Gitter to Slack.

Update: It's also possible to view the messages as a feed on the website - https://view.matrix.org/room/!zjSBLlUkYiQKGGCyTt:gitter.im/

**Comment by julianpistorius** [comment]
@lwdozal we can embed a Twitter feed: https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

**Comment by hidyverse** [comment]
My preference is gitter > X largely because of the topics @Aariq brought up [here](https://github.com/resbazaz/organization/issues/38)

**Comment by lwdozal** [comment]
OK! how do we get gitter onto the website? Or how can we get participants onto it so we can communicate. Should we include this in our last push of messaging tomorrow? Sorry I'm V new to gitter.

**Comment by Aariq** [comment]
There are several built-in ways to add "comments" to Quarto pages, although I suspect this is not quite what we want. https://quarto.org/docs/output-formats/html-basics.html#commenting

**Comment by julianpistorius** [comment]
I recommend:

1. Use an HTML `iframe` element to embed the read-only Gitter messages view for ResBaz/Arizona (see the link I posted above) into the conference page (and possibly the home page)
2. Add a link to the ResBaz/Arizona Gitter channel just above the embedded Gitter messages view. Gitter should prompt people to sign up/log in. 
3. Email attendees information about Gitter, and the link to the ResBaz/Arizona Gitter channel.

This way anyone who visits the website can read the most recent event chatter without needing to log in to Gitter, but there is a link that they can follow to take part if they want to. 

How does that sound?

**Comment by julianpistorius** [comment]
Currently there is no information about the event sessions. What do folks think about creating individual HackMD docs for each session, and linking to them from the schedule Google Sheet (similar to the unconference sessions which link to self-signup Google Sheets.)

Each HackMD can contain the speaker bio, background information, learning outcomes (if a workshop), etc. We can link to the 'read' view for each HackMD (to avoid confusing people with a full Markdown editor.)

I believe HackMD makes it easy to embed a HackMD document into a website. That way we don't need to send people to a different site to view up-to-date event information. 

Thoughts?

**Comment by Aariq** [comment]
Yes, let's do that.  I'd love to have a space to take notes or at least get contact info for attendees should they wish to provide it

**Comment by lwdozal** [comment]
So, for communication with participants I'll send out information of where to find the Gitter feed and HackMD docs each day in an email? Will have some drafts ready that will go out each day.

**Comment by julianpistorius** [comment]
@lwdozal & @Aariq I've created the HackMDs for each session and linked them from the schedule.

Can we please let the presenters know so they can add any links and resources there? They can use it to whatever extent they want, including for notes, slides, etc.

Day 1 (Virtual):

- https://hackmd.io/@ResBazAZ/2024-HPC-Intro
- https://hackmd.io/@ResBazAZ/2024-Local-LLMs
- https://hackmd.io/@ResBazAZ/2024-Stats-Matlab
- https://hackmd.io/@ResBazAZ/2024-QuantFin
- https://hackmd.io/@ResBazAZ/2024-DataViz

Day 3 (In-person):

- https://hackmd.io/@ResBazAZ/2024-LLM-Articles-Chat
- https://hackmd.io/@ResBazAZ/2024-First-Shiny-App
- https://hackmd.io/@ResBazAZ/2024-Jetstream2
- https://hackmd.io/@ResBazAZ/2024-Quarto
