### ISSUE TITLE
Contact helpers

### ISSUE THREAD

**Issue by hidyverse** [resbazaz/festival2024#26]
5 helpers (so far) need to be contacted with ome info regarding resbaz volunteering 
we have docs on this from previous years?

**Comment by hidyverse** [comment]
What do we need helpers to do???

**Comment by lwdozal** [comment]
Virtual helpers: answer people in the comments and help facilitate/host presentations?

in-person helpers: help participants with bugs, downloads and installations to keep flow of presentation; answer logistical questions?

**Comment by hidyverse** [comment]
Contacted!
