### ISSUE TITLE
Initial advertising blast

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2024#4]
I received a message from @TinaJAZ asking whether we have a small "ramping up for the 2024 Festival" blurb to include in the next issue of The Data Drip newsletter. I've asked when the deadline is. 

This is probably something we could reuse and spread far & wide. 

What do you think @lwdozal?

**Comment by lwdozal** [comment]
This sounds great! I'll start writing something up and send it out for you all to look over.

**Comment by lwdozal** [comment]
Here is a ChatGPT-inspired blurb draft. Please comment and edit as you see fit!!

ResBaz 2024: A Call to Innovators and Researchers!

We're thrilled to announce the return of ResBaz (Research Bazaar) 2024! Hosted right here at the University of Arizona, ResBaz champions cutting-edge digital literacy powering today's research frontier which accommodates the needs and preferences of our community members.

ResBaz 2024 will be an arena of collaboration and creativity where researchers from diverse disciplines gather to learn, share, and inspire. This year promises to be more engaging than ever with one day in-person and one day virtual, both days brimming with opportunities to enhance your digital research tools and skills. 

**Who Should Attend?**
ResBaz is open to everyone passionate about research and innovation. Whether you're a seasoned digital researcher, a PhD or research master’s student, or a research technologist, this festival is the perfect venue to broaden your digital horizons. We particularly encourage students and professionals at all levels and from all disciplines to join us in this unique learning experience.

**Why Attend?**
- Learn Next-Gen Skills: Dive into workshops and sessions led by experts to master the latest digital research tools and techniques.
- Collaborate and Network: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
- Share Your Knowledge: Have something to teach? ResBaz is the perfect platform to share your skills and contribute to the collective learning experience.
- Have Fun: Yes, research can be fun! Engage in exciting activities, contests, and social events designed to make learning enjoyable and memorable.
As we continue to navigate the evolving landscape of modern research, ResBaz 2024 stands as a beacon of innovation and community. Stay tuned for more details on how you can be a part of this transformative event.

Check out the [ResBaz2023 program](https://researchbazaar.arizona.edu/resbaz/Arizona2023/) to see what you can expect from this conference.!

**Comment by lwdozal** [comment]
Or wait, should I send this out to slack or our discussion board?

**Comment by TinaJAZ** [comment]
Will the other AZ universities host ResBaz at their institutions? Is it ResBaz or ResBaz AZ? What month is ResBaz?
What is this blurb for - pick and choose what one needs depending on the purpose? I tried to tighten it up a bit. 

**Announcing ResBaz 2024: A Call to Innovators and Researchers!**

The University of Arizona will host ResBaz (Research Bazaar) 2024. As always, ResBaz is an arena of collaboration and creativity where researchers from diverse disciplines gather to learn, share, and inspire. This year’s two-day festival promises to be more engaging than ever with _one day in-person_ and _one day virtual_, **but** both days brimming with opportunities to enhance your digital research tools and skills.

**Yes, You Should Attend**
Students and professionals from all disciplines are encouraged to join us. ResBaz is open to anyone passionate about research and innovation – seasoned digital researchers, PhD or research master’s students, research technologists, and the digital literacy curious. This ResBaz festival is the perfect venue to broaden your digital horizons. 

**Why You Should Attend**
- **Learn Next-Gen Skills**: Dive into workshops and sessions led by experts to master the latest digital research tools and techniques.
- **Collaborate and Network**: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
- **Share Your Knowledge**: Have something to teach? ResBaz is the perfect platform to share your skills and contribute to the collective learning experience.
- **Have Fun**: Yes, research can be fun! Engage in exciting activities, contests, and social events.

ResBaz 2024 is innovative and community-centered. Stay tuned for more details on how you can be a part of this transformative event.

Check out the [ResBaz2023 program](https://researchbazaar.arizona.edu/resbaz/Arizona2023/) to see what you can expect at this year’s RezBaz festival!

**Comment by julianpistorius** [comment]
> @lwdozal: Or wait, should I send this out to slack or our discussion board?

This is a fine place to discuss this. Feel free to post the link to this issue in Slack & the discussion board though.

**Comment by TinaJAZ** [comment]
Is there a ResBazAZ and/or ResBaz Festival logo?

**Comment by hidyverse** [comment]
Hi @TinaJAZ - I'm tagging you in the slack where I posted logos. You can also find them [in this directory](https://github.com/resbazaz/resbazaz_promotional_materials).

**Comment by hidyverse** [comment]
Hi @TinaJAZ and @lwdozal I copied your draft announcement over to a hackmd in case it's easier to collab there. 
https://hackmd.io/@Y70LO71ESz2J0WloxAlrTQ/Hy2xs2Rsp/edit 
This link is at the top of our planning committee notes.

**Comment by lwdozal** [comment]
> Hi @TinaJAZ and @lwdozal I copied your draft announcement over to a hackmd in case it's easier to collab there. https://hackmd.io/@Y70LO71ESz2J0WloxAlrTQ/Hy2xs2Rsp/edit This link is at the top of our planning committee notes.

This is great! Thank you @hidyverse

**Comment by lwdozal** [comment]
Hello!! here is the Initial Save-the-Date Email/Slack message I will be sending out next Monday, please let me know if it needs more tweaking. PS I didn't include anything about NAU or ASU and figured we can include them in later emails.

**Subject**: Announcing ResBaz AZ 2024: A Call to Innovators and Researchers!

[ResBaz](https://researchbazaar.arizona.edu/) AZ‘s annual data science festival, 2024, where researchers come together to level-up in digital research tools and skills will be hosted Wednesday, May 15 - Friday, May 17. In the spirit of a marketplace or bazaar, the Research Bazaar, ResBaz is a highly collaborative event where anyone, regardless of discipline or previous experience, can learn, share knowledge, find help, and have fun!

This year’s FREE three-day festival promises to be more engaging than ever for data beginners and digital experts alike with all three days brimming with opportunities to enhance your digital research tools and skills. The general three-day set-up is:

_**May 15**: Online Conference
**May 16:** Unconference in-person
**May 17**: Traditional Conference in-person_

Why You Should Attend
- Learn Next-Gen Skills: Dive into workshops and sessions led by data experts to master the latest digital research tools and techniques.
- Collaborate and Network: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
- Share Your Knowledge: Have something to teach? ResBaz Festival is the perfect platform to share your skills and contribute to the collective learning experience.
- Have Fun: Yes, research can be fun! Engage in exciting activities, contests, and social events.

ResBaz Festival 2024 is innovative and community-centered. Keep an eye out for speaker and volunteer opportunities, and in the meantime, check out the[ ResBaz 2023 program](https://researchbazaar.arizona.edu/resbaz/Arizona2023.html) to see what you can expect at this year’s #ResBaz2024 festival!

**Comment by lwdozal** [comment]
Also, here's a Prospective Instructors/Facilitators Email taken from last year's verbiage (thanks Val!!)

**Subject**: Research Bazaar 2024 (ResBaz): Call for Instructors, Facilitators and  Volunteers

Hi all,

I am a member of the ResBaz AZ 2024 festival organizing committee. [ResBaz AZ](https://researchbazaar.arizona.edu/resbaz/Arizona2023/), short for Research Bazaar Arizona, is a community and an annual festival-style event that promotes data science literacy across Arizona. 


The 6th annual ResBaz AZ festival is happening Wednesday, May 15 - Friday, May 17, 2024. This free, community driven, and highly collaborative event provides members of the university and surrounding communities with opportunities to “level up” in computational and digital tools for research.


We are seeking instructors and facilitators at UArizona, ASU, NAU, and other Arizona research facilities. Specifically, we are looking for volunteers (grad students, post-docs, faculty, etc.) who would be willing to hold/teach/lead a 30-120 minute workshop on a data science topic, or facilitate an unconference session that is a creative and collaborative endeavor. ResBaz AZ’s annual festival is a great opportunity to expand teaching experience in a low stakes and welcoming environment. 


Please fill out our **survey** relaying your interest in teaching a workshop, facilitating an unconference session or volunteering your time. You are also encouraged to share the survey with other potential educators. 

Thank you for your consideration! 

[your name here]
http://arizona.researchbazaar.org/

**Comment by lwdozal** [comment]
I also added both to the github here: https://github.com/resbazaz/festival2024/commit/9287aeb880616ef5ceff6b8c228e65e4c1443e0f

**Comment by TinaJAZ** [comment]
Again, yes, I missed an important meeting. Here’s my input.

Advertising needs to be kept short. Too much trying to define what ResBaz and ResBaz AZ are loses the attention of those who might be interested in attending and it just gets in the way of those who are already familiar. Define them on the website and give some clarity to what and how “level up” means.

Subject: Announcing ResBaz AZ 2024: A Call to Innovators and Researchers!  Perhaps, I am misunderstanding, but the message below is not a call for innovators or researchers. It is merely a save-the-date announcement. At this time, they cannot register to attend or sign up to be a speaker or a volunteer. If it’s a call, it’s a call to hold the date on their calendars and make note of what ResBaz is. If you don’t tell people to put a hold on their calendar now, they will forget. Granted, there are no guarantees that they will  save the date either. Where are the in-person activities taking place?

Subject: Join Us - ResBaz 2024 for Innovators and Researchers!

SAVE-THE-DATE  /  JOIN US  /  SAVE-THE-DATE

ResBaz 2024<https://researchbazaar.arizona.edu/> – May 15-17 (– taking place here, where are in-person events?)

ResBaz AZ hosts the annual data science festival, ResBaz, where researchers come together in the spirit of a marketplace or bazaar to level-up in computational and digital research tools and skills. The ResBaz festival is a highly collaborative event where anyone, regardless of discipline or previous experience, can learn, share knowledge, find help, and have fun!  Innovative and community-centered with a commitment to inclusiveness, the festival is scheduled slightly different each day and is open to all:

May 15: Online Conference
May 16: Unconference in-person
May 17: Traditional Conference in-person

Why You Should Join Us

  *   Learn Next-Gen Skills: Dive into workshops and sessions led by data experts to master the latest digital research tools and techniques.
  *   Collaborate and Network: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
  *   Share Your Knowledge: Have something to teach? The ResBaz festival is the perfect platform to share your skills and contribute to the collective learning experience.
  *   Have Fun: Yes, research can be fun! Engage in exciting activities, contests, and social events.

Put a hold on your calendar for ResBaz 2024 – May 15-17 and note that registration opens in ___???___.  Look for speaker and volunteer opportunities coming soon. In the meantime, check out the ResBaz 2023 program<https://researchbazaar.arizona.edu/resbaz/Arizona2023.html> to see what you can expect at this year’s #ResBaz2024 festival!



From: Laura W. Dozal ***@***.***>
Sent: Wednesday, March 6, 2024 3:20 PM
To: resbazaz/festival2024 ***@***.***>
Cc: Johnson, Tina L - (tina) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [resbazaz/festival2024] Initial advertising blast (Issue #4)


External Email

Hello!! here is the Initial Save-the-Date Email/Slack message I will be sending out next Monday, please let me know if it needs more tweaking. PS I didn't include anything about NAU or ASU and figured we can include them in later emails.

Subject: Announcing ResBaz AZ 2024: A Call to Innovators and Researchers!

ResBaz<https://researchbazaar.arizona.edu/> AZ‘s annual data science festival, 2024, where researchers come together to level-up in digital research tools and skills will be hosted Wednesday, May 15 - Friday, May 17. In the spirit of a marketplace or bazaar, the Research Bazaar, ResBaz is a highly collaborative event where anyone, regardless of discipline or previous experience, can learn, share knowledge, find help, and have fun!

This year’s FREE three-day festival promises to be more engaging than ever for data beginners and digital experts alike with all three days brimming with opportunities to enhance your digital research tools and skills. The general three-day set-up is:

May 15: Online Conference
May 16: Unconference in-person
May 17: Traditional Conference in-person

Why You Should Attend

  *   Learn Next-Gen Skills: Dive into workshops and sessions led by data experts to master the latest digital research tools and techniques.
  *   Collaborate and Network: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
  *   Share Your Knowledge: Have something to teach? ResBaz Festival is the perfect platform to share your skills and contribute to the collective learning experience.
  *   Have Fun: Yes, research can be fun! Engage in exciting activities, contests, and social events.

ResBaz Festival 2024 is innovative and community-centered. Keep an eye out for speaker and volunteer opportunities, and in the meantime, check out the ResBaz 2023 program<https://researchbazaar.arizona.edu/resbaz/Arizona2023.html> to see what you can expect at this year’s #ResBaz2024 festival!

**Comment by lwdozal** [comment]
ok, I'll send out this email/slack message on Tuesday morning? We have a registration form but waiting to see if it's ready to go. If we get the ok on the initial registration form I'll change the verbiage to "sign-up" instead of "Save the date"

Subject: Announcing ResBaz AZ 2024: Save the date for Innovators and Researchers!

ResBaz AZ hosts the annual data science festival, ResBaz, where researchers come together in the spirit of a marketplace or bazaar to level-up in computational and digital research tools and skills. The ResBaz festival is a highly collaborative event where anyone, regardless of discipline or previous experience, can learn, share knowledge, find help, and have fun!  Innovative and community-centered with a commitment to inclusiveness, the festival is scheduled slightly different each day and is open to all:

May 15: Online Conference
May 16: Unconference in-person
May 17: Traditional Conference in-person

Why You Should Join Us

  *   Learn Next-Gen Skills: Dive into workshops and sessions led by data experts to master the latest digital research tools and techniques.
  *   Collaborate and Network: Connect with like-minded researchers from various fields, fostering interdisciplinary collaboration and community building.
  *   Share Your Knowledge: Have something to teach? The ResBaz festival is the perfect platform to share your skills and contribute to the collective learning experience.
  *   Have Fun: Yes, research can be fun! Engage in exciting activities, contests, and social events.

Put a hold on your calendar for ResBaz 2024 – May 15-17 and registration opens next week! Want to get involved? Look for speaker and volunteer opportunities coming soon. 
In the meantime, check out the ResBaz 2023 program<https://researchbazaar.arizona.edu/resbaz/Arizona2023.html> to see what you can expect at this year’s #ResBaz2024 festival!

**Comment by lwdozal** [comment]
@channel I'm going to use the our resbaz email to send out the initial registration blast, but I'm wondering who to send it to!!! Should I give you all the final version so we send it our respective departments, or would you like to provide a list of emails for me to contact?

**Comment by lwdozal** [comment]
I'm actually just going to send out an initial save the date memo without the form because the forms asks users to check which day they want to participate, but we don't have set sessions or workshops yet so I'm not sure people would know when they want to show up. For example, I usually participate if I'm interested in a specific topic and not the day.

**Comment by hidyverse** [comment]
Hi Laura thanks for all your work on this! Let me try to address some of your concerns, here. 
> I'm actually just going to send out an initial save the date memo without the form  

Let's focus on getting the save the date to Tina at DSI for the Data Drip as priority #1. If you have some initial departments to share with, that's great. Let's go ahead and make a list of who we email (in slack for now). 
I agree it can go out without the form. 

> would you like to provide a list of emails for me to contact?

I think this is a good idea! Can you solicit slack #resbaz2024 or even #general channels for thoughts on who to spam with save the dates/registration emails? 

> going to use the our resbaz email

I've drafted your email there with some updates! LMK if you can't see it.
